version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Check docker"
          command:
            ./run
          no_output_timeout: 600m
