version: 2.1



jobs:
  build:
    macos:
      xcode: 11.3.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            ./run
